# Generated by Django 4.2.2 on 2023-06-21 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='текст вопроса')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='ответ')),
                ('asked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='задан')),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('CON', 'На рассмотрении'), ('CLO', 'Закрыт')], db_index=True, default='NEW', max_length=3, verbose_name='Статус')),
                ('from_whom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues_from', to=settings.AUTH_USER_MODEL, verbose_name='от кого')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='tg_bot.report', verbose_name='доклад')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
    ]
