# Generated by Django 4.2.2 on 2023-06-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatState',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='идентификатор чата')),
                ('state', models.CharField(max_length=100, verbose_name='состояние')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создан в')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='изменен в')),
            ],
            options={
                'verbose_name': 'состояние чата',
                'verbose_name_plural': 'состояния чатов',
            },
        ),
    ]
