# Generated by Django 4.2.2 on 2023-06-26 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0006_delete_chatstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_number', models.IntegerField(blank=True, null=True, verbose_name='число')),
            ],
        ),
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_is_current', models.BooleanField(blank=True, null=True, verbose_name='статус')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watcher', to='tg_bot.report', verbose_name='доклад')),
            ],
        ),
    ]
