# Generated by Django 4.2.2 on 2023-06-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0007_count_watcher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watcher',
            name='status_is_current',
        ),
    ]
