# Generated by Django 4.2.2 on 2023-06-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0008_remove_watcher_status_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='current_number',
            field=models.IntegerField(null=True, verbose_name='число'),
        ),
    ]
