# Generated by Django 4.2.2 on 2023-06-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0009_alter_count_current_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='current_number',
            field=models.IntegerField(default=0, null=True, verbose_name='число'),
        ),
    ]
