# Generated by Django 4.2.2 on 2023-06-26 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0010_alter_count_current_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watcher',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watcher', to='tg_bot.report', verbose_name='доклад'),
        ),
    ]
